GitHub Actions (MSP-Greg) + Ruby 3.0 support
knu/ruby-unf_ext pull request #64
Opened 2021-08-29 05:32 UTC by johnnyshields

This includes commits from #59 plus adds Ruby 3.0 support

2021-09-02 05:17 UTC, knu requested changes
Thanks!

I'd like style changes separated from functional changes because it's hard to review when the two types of changes mixed.

2021-09-02 05:17 UTC, knu commented on lib/unf_ext/version.rb
> +    VERSION = "0.0.7.8"
Could you remove this change?

2021-09-02 05:17 UTC, knu commented on unf_ext.gemspec
> +  gem.add_development_dependency('rake-compiler-dock', ['>= 1.0.1'])
Please keep the diff to a minimum.

2021-09-02 06:07 UTC, johnnyshields commented on CHANGELOG.md
> +## 0.0.7.8 (2021-08-29)
Done.

2021-09-02 06:08 UTC, johnnyshields commented on lib/unf_ext/version.rb
> +    VERSION = "0.0.7.8"
Done > reverted

2021-09-02 06:08 UTC, johnnyshields commented on unf_ext.gemspec
> +  gem.add_development_dependency('rake-compiler-dock', ['>= 1.0.1'])
Done > Diff minimized.

2021-09-02 06:10 UTC, johnnyshields commented
@knu I think it's difficult to support Ruby < 2.2 on Github Actions, that's the reason for dropping it.

Since the published versions of this gem support older Ruby, and Ruby 2.1 was EOL in 2017, it's probably not an issue.

2021-09-06 07:04 UTC, knu reviewed
Thanks!  I think I can squash and split the commits into meaningful sets of hunks, but do you intend to do that yourself?

2021-09-06 08:37 UTC, johnnyshields commented
@knu I've squashed the commits and included @MSP-Greg 's original commit.

2021-09-14 02:53 UTC, knu approved these changes
Thanks!  I'm merging this and will prepare for a new release.

2021-09-14 02:54 UTC, merged